version: "3.9"

services:
  db:
    container_name: db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "dev"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Tokyo"
    ports:
      - "3308:3306"
    expose:
      - "3306"
    volumes:
      - ./db/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src
    ports:
      - 8080:8080
    depends_on:
      - db
